/*
    Create slideshows from Inkscape SVG files
    Copyright (C) 2023-2025 Sylvain Hallé

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ca.leduotang.inkscapeslide;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpressionException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import ca.uqac.lif.bullwinkle.BnfParser;
import ca.uqac.lif.bullwinkle.BnfParser.InvalidGrammarException;
import ca.uqac.lif.bullwinkle.BnfParser.ParseException;
import ca.uqac.lif.bullwinkle.ParseNode;
import ca.uqac.lif.bullwinkle.ParseTreeObjectBuilder.BuildException;

/**
 * Interprets the commands contained in an SVG document to produce
 * a slideshow.
 */
public class CommandInterpreter extends SvgProcessor
{
	/**
	 * The list of layers currently being displayed in the current
	 * slide.
	 */
	protected final List<LayerOccurrence> m_currentLayers;

	/**
	 * The layers considered as a template, and which are to be
	 * included in every slide.
	 */
	protected final List<LayerOccurrence> m_templateLayers;

	/**
	 * The list of commands parsed from the SVG file.
	 */
	protected final List<Command> m_commands;

	/**
	 * The current page number of the slideshow being generated
	 * by the interpreter.
	 */
	protected int m_pageNumber;

	/**
	 * Creates a new command interpreter for the given SVG document.
	 * @param doc The SVG document
	 * @throws CommandException If an error occurs while parsing the
	 * commands
	 */
	public CommandInterpreter(Document doc) throws CommandException
	{
		super(doc);
		m_currentLayers = new ArrayList<LayerOccurrence>();
		m_templateLayers = new ArrayList<LayerOccurrence>();
		m_commands = new ArrayList<Command>();
		try
		{
			Node n = (Node) m_xpath.compile("//g[@groupmode='layer' and @label='content']").evaluate(doc, XPathConstants.NODE);
			parseInstructions(n);
		}
		catch (XPathExpressionException | InvalidGrammarException e)
		{
			// Should not happen, since the XPath expression *is* valid
			// and the grammar file *is* valid
		}
	}
	
	public List<String> getAllLayerNames()
	{
		return new ArrayList<String>(m_layers.keySet());
	}

	/**
	 * Indicates that the interpreter should move to the next page. This method
	 * is called by commands that create new slides.
	 */
	public void incrementPageNumber()
	{
		m_pageNumber++;
	}

	/**
	 * Gets the current page number.
	 * @return The current page number
	 */
	public int getPageNumber()
	{
		return m_pageNumber;
	}

	/**
	 * Parses the instructions contained in the given node, according to the
	 * grammar defined in grammar.bnf.
	 * @param n The node containing the instructions
	 * @throws CommandException If an error occurs during parsing
	 * @throws InvalidGrammarException If the grammar file is invalid
	 */
	protected void parseInstructions(Node n) throws InvalidGrammarException, CommandException
	{
		BnfParser parser = new BnfParser(CommandInterpreter.class.getResourceAsStream("grammar.bnf"));
		NodeList lines = null;
		try
		{
			lines = (NodeList) m_xpath.compile("text/tspan[text()]").evaluate(n, XPathConstants.NODESET);
		}
		catch (XPathExpressionException e)
		{
			// Should not happen, since the XPath expression *is* valid
		}
		for (int i = 0; i < lines.getLength(); i++)
		{
			Node n_line = lines.item(i);
			String line = n_line.getTextContent().trim();
			ParseNode tree;
			if (line.isEmpty())
			{
				continue;
			}
			try
			{
				tree = parser.parse(line);
			}
			catch (ParseException e)
			{
				throw new CommandException(e, i);
			}
			CommandBuilder builder = new CommandBuilder();
			Command c;
			try
			{
				c = builder.build(tree);
				m_commands.add(c);
			}
			catch (BuildException e)
			{
				throw new CommandException(e, i);
			}
		}
	}

	/**
	 * Gets the list of slides generated by the interpreter.
	 * @return The list of slides, as SVG documents
	 */
	public List<Document> getSlides()
	{
		return m_slides;
	}

	/**
	 * Out of a Slide object, generates the corresponding SVG document.
	 * @param slide The slide to generate
	 * @return The SVG document corresponding to the slide
	 * @throws XPathExpressionException If an error occurs while querying
	 * the SVG document
	 */
	public Document getSvgSlide(Slide slide) throws XPathExpressionException
	{
		Document new_doc = s_builder.newDocument();
		Node orig_root = (Node) m_xpath.compile("svg").evaluate(m_document, XPathConstants.NODE);
		Node svg_root = orig_root.cloneNode(false);
		new_doc.adoptNode(svg_root);
		new_doc.appendChild(svg_root);
		{
			Node orig = (Node) m_xpath.compile("svg/defs").evaluate(m_document, XPathConstants.NODE);
			Node new_n = orig.cloneNode(true);
			new_doc.adoptNode(new_n);
			svg_root.appendChild(new_n);
		}
		{
			Node orig = (Node) m_xpath.compile("svg/namedview").evaluate(m_document, XPathConstants.NODE);
			Node new_n = orig.cloneNode(true);
			new_doc.adoptNode(new_n);
			svg_root.appendChild(new_n);
		}
		{
			Node orig = (Node) m_xpath.compile("svg/metadata").evaluate(m_document, XPathConstants.NODE);
			if (orig == null)
			{
				// Some SVG files use the Inkscape namespace for metadata
				orig = (Node) m_xpath.compile("svg/inkscape:metadata").evaluate(m_document,
						XPathConstants.NODE);
			}
			if (orig != null)
			{
				Node new_n = orig.cloneNode(true);
				new_doc.adoptNode(new_n);
				svg_root.appendChild(new_n);
			}
		}
		for (LayerOccurrence lo : slide)
		{
			int index = getIndex(lo.getName());	
			if (index == -1)
			{
				throw new IllegalArgumentException("No layer named " + lo.getName());
			}
			lo.m_order = getIndex(lo.getName());
		}
		Collections.sort(slide);
		for (LayerOccurrence lo : slide)
		{
			if (m_layers.containsKey(lo.getName()))
			{
				Layer l = m_layers.get(lo.getName());
				Element new_n = (Element) l.getContent().cloneNode(true);
				applyReplacements(new_n);
				new_n.setAttribute("style", "");
				if (lo.getAlpha() < 1)
				{
					new_n.setAttribute("opacity", Float.toString(lo.getAlpha()));
				}
				new_doc.adoptNode(new_n);
				svg_root.appendChild(new_n);
			}
		}
		return new_doc;
	}

	protected void applyReplacements(Element e)
	{
		NodeList list = e.getChildNodes();
		for (int i = 0; i < list.getLength(); i++)
		{
			Node n = list.item(i);
			if (n.getTextContent().compareTo("@P") == 0)
			{
				n.setTextContent(Integer.toString(m_pageNumber));
			}
		}
	}

	/**
	 * Gets the index of the layer with the given name.
	 * @param layer_name The name of the layer
	 * @return The index of the layer, or -1 if no such layer exists
	 */
	protected int getIndex(String layer_name)
	{
		if (!m_layers.containsKey(layer_name))
		{
			return -1;
		}
		return m_layers.get(layer_name).getIndex();
	}

	/**
	 * Gets the list of layers currently being displayed in the slide.
	 * @return The list of current layers
	 * @see #m_currentLayers
	 */
	public List<LayerOccurrence> getCurrentLayers()
	{
		return m_currentLayers;
	}

	/**
	 * Gets the list of template layers.
	 * @return The list of template layers
	 * @see #m_templateLayers
	 */
	public List<LayerOccurrence> getTemplateLayers()
	{
		return m_templateLayers;
	}

	public void setCurrentLayers(List<LayerOccurrence> layers)
	{
		m_currentLayers.clear();
		m_currentLayers.addAll(layers);
	}

	public void addCurrentLayers(List<LayerOccurrence> layers)
	{
		m_currentLayers.addAll(layers);
	}

	public void xorCurrentLayers(List<LayerOccurrence> layers)
	{
		for (LayerOccurrence lo : layers)
		{
			if (m_currentLayers.contains(lo))
			{
				m_currentLayers.remove(lo);
			}
			else
			{
				m_currentLayers.add(lo);
			}
		}
	}

	public void deleteCurrentLayers(List<LayerOccurrence> layers)
	{
		m_currentLayers.removeAll(layers);
	}

	public void setTemplateLayers(List<LayerOccurrence> layers)
	{
		m_templateLayers.clear();
		m_templateLayers.addAll(layers);
	}

	/**
	 * Creates a new slide out of the current layers and template layers,
	 * and adds it to the list of slides.
	 * @throws XPathExpressionException If an error occurs while querying
	 * the SVG document
	 */
	public void outputSlide() throws XPathExpressionException
	{
		Slide slide = new Slide();
		slide.addAll(m_templateLayers);
		slide.addAll(m_currentLayers);
		m_slides.add(getSvgSlide(slide));
	}

	/**
	 * Interprets the list of commands parsed from the SVG file.
	 * @throws CommandException If an error occurs during interpretation
	 * @see #m_commands
	 */
	public void interpret() throws CommandException
	{
		for (Command c : m_commands)
		{
			c.interpret(this);
		}
	}
}
