<S>            := <instruction> | <comment> | <slide> ; 

<slide>        := <additive> | <subtractive> | <xor> | <loop> | <normal> ;
<normal>       := <layers> ;
<subtractive>  := - <layers> ;
<additive>     := + <layers> ;
<xor>          := * <layers> ;
<loop>         := <l_additive> | <l_xor> | <l_normal> ;
<l_additive>   := %+ <pattern> ;
<l_xor>        := %* <pattern> ;
<l_normal>     := % <pattern> ;
<layers>       := <layer> , <layers> | <layer> ;
<layer>        := <layername> * <alpha> | <layername> ;
<layername>    := ^[\w\-]+;
<slidename>    := ^[\w\-]+;
<pattern>      := ^.*;
<alpha>        := ^[\d\.]+;

<instruction>  := @ <instbody> ;
<instbody>     := <template> ;
<template>     := template: <layers> ;

<comment>      := ^//.*;